<!DOCTYPE html>
<html lang="es-Mx" ng-app="front">
<head>
    <base href="/"/>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SPECTRUM | DIVISIÓN DE CAPACITACIÓN</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/front/src/images/icon.png">
    <!--Fonts-->
    <link rel="stylesheet" id="Google-Font-css" href="http://fonts.googleapis.com/css?family=Droid+Sans%3An%2Ci%2Cb%2Cbi%7CDroid+Serif%3An%2Ci%2Cb%2Cbi%7CExo%3An%2Ci%2Cb%2Cbi%7C&amp;ver=4.1.7" type="text/css" media="all">
    <?= $this->assets->outputCss("IndexCss")?>

    <!--[if lt IE 9]>
    <script src="<?=$this->url->get('front/src/js/html5shiv-printshiv.js')?>"></script>
    <script src="<?=$this->url->get('front/src/js/respond.min.js')?>"></script>
    <![endif]-->

</head>
<body class="default home">
    <header class="row">
        <div class="top_row row m0">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 tagLine">
                        <i class="fa fa-smile-o"></i> Servicios Técnicos de México
                    </div>
                    <div class="col-sm-6">
                        <ul class="nav navbar-right">
                            <li><a href="<?=$this->url->get('login');   ?>"><img src="/front/src/images/icons/top-bar/user.png" alt="">Iniciar Sesión</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!--Top Row-->
        <div class="logo_row row m0">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <a href="index.html" class="logo">
                            <img src="/front/src/images/LogoSpectrum.png" alt="">
                        </a>
                    </div>
                    <div class="col-sm-8">
                        <ul class="nav">
                            <li><a href="#"><span class="icon phone"></span>(+52) 993 316 02 87 y 993 316 19 59</a></li>
                            <li><a href="mailto:capacitacion@spectrumstm.com"><span class="icon email"></span>capacitacion@spectrumstm.com &nbsp;&nbsp;</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!--Logo Row-->
        <nav class="row menu_row m0">
            <div class="container">
                <div class="row">
                    <div class="search_form_area fright">
                        <form action="#" class="col-sm-6 search_form p0" method="get">
                            <div class="input-group">
                                <input type="search" class="form-control">
                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            </div>
                        </form>
                        <a href="#" class="col-sm-6 free_analysis">
                            <img src="/front/src/images/icons/menu/free_analysis.png" alt=""> SPECTRUM
                        </a>
                    </div> <!--Search And Analysis-->
                    <div class="fleft menu_area">
                        <button class="btn btn-primary visible-xs" type="button" data-toggle="collapse" data-target="#mainMenu" aria-expanded="false" aria-controls="mainMenu">
                            <i class="glyphicon glyphicon-th-large"></i> Menu
                        </button>
                        <div class="collapse navbar-collapse" id="mainMenu" ng-controller="IndexController">
                            <ul class="nav navbar-nav">
                                <li class="dropdown" ng-class="{'active':$location.path()=='/'}">
                                    <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">INICIO</a>
                                    <!--ul class="dropdown-menu">
                                        <li><a href="index.html">Home</a></li>
                                        <li><a href="index2.html">Home 2</a></li>
                                    </ul-->
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CURSOS</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">TODOS LOS CURSOS</a></li>
                                        <li><a href="#">CATÁLOGO DE CURSOS</a></li>
                                        <li><a href="#">CURSOS FINALIZADOS</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">GALERÍA</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">VIDEOS</a></li>
                                        <li><a href="#">IMÁGENES</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ACERCA DE</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">NOSOTROS</a></li>
                                        <li><a href="#">VISIÓN-MISIÓN</a></li>
                                        <li><a href="#">HISTORIA</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown" ng-class="{'active':$location.path()=='/contactanos'}">
                                    <a href="<?=$this->url->get('contactanos')?>">CONTACTANOS</a>
                                </li>
                            </ul>
                        </div>
                    </div> <!--Menu Area-->
                </div>
            </div>
        </nav> <!--Menu Row-->
    </header>
    <div ng-view></div>
    <footer class="row">
        <div class="row m0 top_footer">
            <div class="container">
                <div class="row footer_widgets">
                    <div class="col-sm-4 footer_widget">
                        <div class="row m0">
                            <h4 class="title">Acerca de Nosotros</h4>
                            <div class="row m0 body">
                                <p>Somos una empresa de consultoría especializada para el área de hidrocarburos y energía en general. Ofrecemos a nuestros clientes asistencia técnica en las áreas de exploración, producción y operación de yacimientos de hidrocarburo, así como capacitación especializada, diplomados y certificaciones para personal técnico y administrativo.</p><br>
                                <ul class="nav socials">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="https://twitter.com/SpectrumSTM"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                    <li><a href="https://www.linkedin.com/company/1319788?trk=prof-0-ovw-curr_pos"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#"><i class="fa fa-rss"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div> <!--Single widget-->
                    <div class="col-sm-4 footer_widget">
                        <div class="row m0">
                            <h4 class="title">Suscríbete</h4>
                            <div class="row m0 body">
                                <!-- Begin MailChimp Signup Form -->
                                <div id="mc_embed_signup" class="row m0">
                                    <p>Recibe nuestras promociones e información de nuevos cursos</p>
                                    <form class="validate mailchimp_form" target="_blank">
                                        <div id="mc_embed_signup_scroll">
                                            <div class="input-group">
                                                <span class="input-group-addon"><img src="/front/src/images/icons/footer/name.png" alt=""></span>
                                                <input type="text" name="name" class="required form-control m0" id="name" placeholder="Nombre">
                                            </div>
                                            <div class="input-group">
                                                <span class="input-group-addon"><img src="/front/src/images/icons/footer/email.png" alt=""></span>
                                                <input type="email" name="email" class="required email form-control m0" id="email" placeholder="Correo">
                                            </div>
                                            <div class="clear">
                                                <button style="height: 58px;" type="submit" name="subscribe" id="mc-embedded-subscribe" class="button btn submit_btn borderred_link"><span>Suscribirse</span></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <!--End mc_embed_signup-->
                            </div>
                        </div>
                    </div> <!--Single widget-->
                    <div class="col-sm-4 footer_widget">
                        <div class="row m0">
                            <h4 class="title">Enlaces recomendados</h4>
                            <div class="row m0 body">
                                <ul class="list-unstyled links">
                                    <li class="fa fa-caret-right"><a href="#">Contactános</a></li>
                                    <li class="fa fa-caret-right"><a href="#">Cursos</a></li>
                                    <li class="fa fa-caret-right"><a href="#">Acerca de nosotros</a></li>
                                    <li class="fa fa-caret-right"><a href="#">Inscripciones</a></li>
                                    <li class="fa fa-caret-right"><a href="#">Promociones</a></li>
                                </ul>
                            </div>
                        </div>
                    </div> <!--Single widget-->
                </div>
                <div class="row footer_widgets2 m0">
                    <ul class="nav nav-justified">
                        <li>
                            <a href="#">
                                <img src="/front/src/images/icons/footer/call.png" alt=""><strong>Telefonos</strong>: (+52) 993 316 02 87 y 993 316 19 59
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/front/src/images/icons/footer/mail.png" alt=""><strong>Correo</strong>: capacitacion@spectrumstm.com
                            </a>
                        </li>
                        <!--li>
                            <a href="#">
                                <img src="/front/src/images/icons/footer/fax.png" alt=""><strong>Fax</strong>: +(61) 123 456 7890
                            </a>
                        </li-->
                    </ul>
                </div>
            </div>
        </div>
        <div class="row copyright m0">Copyright &copy; 2015 <a href="#">Seowave</a>. All Rights Reserved.</div>
    </footer>
    <?= $this->assets->outputJs("Angular")?>
    <?= $this->assets->outputJs("IndexJs")?>
    <script src="//maps.google.com/maps/api/js"></script>
</body>
</html>